// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartStockV1.Data;

#nullable disable

namespace SmartStockV1.Migrations
{
    [DbContext(typeof(SmartStockDbContext))]
    partial class SmartStockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartStockV1.Models.CajaDia", b =>
                {
                    b.Property<int>("CajaDiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CajaDiaId"));

                    b.Property<int>("DiaId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCierre")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalGananciaDia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CajaDiaId");

                    b.HasIndex("DiaId")
                        .IsUnique();

                    b.ToTable("CajaDia");
                });

            modelBuilder.Entity("SmartStockV1.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<DateTime>("FechaCreacionCategoria")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("SmartStockV1.Models.CompraDia", b =>
                {
                    b.Property<int>("CompraDiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraDiaId"));

                    b.Property<int?>("CajaDiaId")
                        .HasColumnType("int");

                    b.Property<int>("DiaId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCompraDia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CompraDiaId");

                    b.HasIndex("CajaDiaId");

                    b.HasIndex("DiaId")
                        .IsUnique();

                    b.ToTable("CompraDia");
                });

            modelBuilder.Entity("SmartStockV1.Models.DetalleCompra", b =>
                {
                    b.Property<int>("DetalleCompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleCompraId"));

                    b.Property<int>("CompraDiaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDetalleCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalDetalleCompra")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("DetalleCompraId");

                    b.HasIndex("CompraDiaId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DetalleCompra");
                });

            modelBuilder.Entity("SmartStockV1.Models.DetalleCompraItem", b =>
                {
                    b.Property<int>("CompraItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraItemId"));

                    b.Property<decimal>("CantidadItem")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DetalleCompraId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioCostoItem")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("CompraItemId");

                    b.HasIndex("DetalleCompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleCompraItem");
                });

            modelBuilder.Entity("SmartStockV1.Models.DetalleVenta", b =>
                {
                    b.Property<int>("DetalleVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleVentaId"));

                    b.Property<DateTime>("FechDetalleVenta")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SubtotalDetalleVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("VentaDiaId")
                        .HasColumnType("int");

                    b.HasKey("DetalleVentaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaDiaId");

                    b.ToTable("DetalleVenta");
                });

            modelBuilder.Entity("SmartStockV1.Models.DetalleVentaItem", b =>
                {
                    b.Property<int>("VentaItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaItemId"));

                    b.Property<decimal>("CantidadItem")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DetalleVentaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioCostoItem")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVentaItem")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("VentaItemId");

                    b.HasIndex("DetalleVentaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleVentaItem");
                });

            modelBuilder.Entity("SmartStockV1.Models.Dia", b =>
                {
                    b.Property<int>("DiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("DiaId");

                    b.ToTable("Dia");
                });

            modelBuilder.Entity("SmartStockV1.Models.MovimientoStock", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoId"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CompraItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoAjuste")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VentaItemId")
                        .HasColumnType("int");

                    b.HasKey("MovimientoId");

                    b.HasIndex("CompraItemId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaItemId");

                    b.ToTable("MovimientoStock");
                });

            modelBuilder.Entity("SmartStockV1.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoBarra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstadoProducto")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioCosto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StockActualProductoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ProductoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("StockActualProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("SmartStockV1.Models.Proveedor", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstadoProveedor")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacionProveedor")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ProveedorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Proveedor");
                });

            modelBuilder.Entity("SmartStockV1.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            NombreRol = "Admin"
                        },
                        new
                        {
                            RolId = 2,
                            NombreRol = "Usuario"
                        });
                });

            modelBuilder.Entity("SmartStockV1.Models.StockActual", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("CantidadStock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltActualizacion")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductoId");

                    b.ToTable("StockActual");
                });

            modelBuilder.Entity("SmartStockV1.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<DateTime>("AltaUsuario")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("ContraseñaHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ContraseñaSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("EstadoUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HoraConexion")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltConexion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("SmartStockV1.Models.VentaDia", b =>
                {
                    b.Property<int>("VentaDiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VentaDiaId"));

                    b.Property<int?>("CajaDiaId")
                        .HasColumnType("int");

                    b.Property<int>("DiaId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalGananciaVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalVentaDia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VentaDiaId");

                    b.HasIndex("CajaDiaId");

                    b.HasIndex("DiaId")
                        .IsUnique();

                    b.ToTable("VentaDia");
                });

            modelBuilder.Entity("SmartStockV1.Models.CajaDia", b =>
                {
                    b.HasOne("SmartStockV1.Models.Dia", "Dia")
                        .WithOne("CajaDia")
                        .HasForeignKey("SmartStockV1.Models.CajaDia", "DiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dia");
                });

            modelBuilder.Entity("SmartStockV1.Models.Categoria", b =>
                {
                    b.HasOne("SmartStockV1.Models.Usuario", "Usuario")
                        .WithMany("CategoriasCreadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartStockV1.Models.CompraDia", b =>
                {
                    b.HasOne("SmartStockV1.Models.CajaDia", "CajaDia")
                        .WithMany()
                        .HasForeignKey("CajaDiaId");

                    b.HasOne("SmartStockV1.Models.Dia", "Dia")
                        .WithOne("CompraDia")
                        .HasForeignKey("SmartStockV1.Models.CompraDia", "DiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CajaDia");

                    b.Navigation("Dia");
                });

            modelBuilder.Entity("SmartStockV1.Models.DetalleCompra", b =>
                {
                    b.HasOne("SmartStockV1.Models.CompraDia", "CompraDia")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("CompraDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStockV1.Models.Proveedor", "Proveedor")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStockV1.Models.Usuario", "Usuario")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompraDia");

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartStockV1.Models.DetalleCompraItem", b =>
                {
                    b.HasOne("SmartStockV1.Models.DetalleCompra", "DetalleCompra")
                        .WithMany("ItemsDetalleCompra")
                        .HasForeignKey("DetalleCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStockV1.Models.Producto", "Producto")
                        .WithMany("DetallesCompraItem")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetalleCompra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SmartStockV1.Models.DetalleVenta", b =>
                {
                    b.HasOne("SmartStockV1.Models.Usuario", "Usuario")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartStockV1.Models.VentaDia", "VentaDia")
                        .WithMany("DetallesVentas")
                        .HasForeignKey("VentaDiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("VentaDia");
                });

            modelBuilder.Entity("SmartStockV1.Models.DetalleVentaItem", b =>
                {
                    b.HasOne("SmartStockV1.Models.DetalleVenta", "DetalleVenta")
                        .WithMany("ItemsDetalleVenta")
                        .HasForeignKey("DetalleVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartStockV1.Models.Producto", "Producto")
                        .WithMany("DetallesVentaItem")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetalleVenta");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SmartStockV1.Models.MovimientoStock", b =>
                {
                    b.HasOne("SmartStockV1.Models.DetalleCompraItem", "CompraItem")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("CompraItemId");

                    b.HasOne("SmartStockV1.Models.Producto", "Producto")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartStockV1.Models.DetalleVentaItem", "VentaItem")
                        .WithMany("MovimientosStock")
                        .HasForeignKey("VentaItemId");

                    b.Navigation("CompraItem");

                    b.Navigation("Producto");

                    b.Navigation("VentaItem");
                });

            modelBuilder.Entity("SmartStockV1.Models.Producto", b =>
                {
                    b.HasOne("SmartStockV1.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartStockV1.Models.StockActual", "StockActual")
                        .WithMany()
                        .HasForeignKey("StockActualProductoId");

                    b.HasOne("SmartStockV1.Models.Usuario", "Usuario")
                        .WithMany("ProductosCreados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("StockActual");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartStockV1.Models.Proveedor", b =>
                {
                    b.HasOne("SmartStockV1.Models.Usuario", "Usuario")
                        .WithMany("ProveedoresCreados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SmartStockV1.Models.StockActual", b =>
                {
                    b.HasOne("SmartStockV1.Models.Producto", "Producto")
                        .WithOne()
                        .HasForeignKey("SmartStockV1.Models.StockActual", "ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SmartStockV1.Models.Usuario", b =>
                {
                    b.HasOne("SmartStockV1.Models.Rol", "Rol")
                        .WithMany("UsuariosCreados")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SmartStockV1.Models.VentaDia", b =>
                {
                    b.HasOne("SmartStockV1.Models.CajaDia", "CajaDia")
                        .WithMany()
                        .HasForeignKey("CajaDiaId");

                    b.HasOne("SmartStockV1.Models.Dia", "Dia")
                        .WithOne("VentaDia")
                        .HasForeignKey("SmartStockV1.Models.VentaDia", "DiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CajaDia");

                    b.Navigation("Dia");
                });

            modelBuilder.Entity("SmartStockV1.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("SmartStockV1.Models.CompraDia", b =>
                {
                    b.Navigation("DetallesCompra");
                });

            modelBuilder.Entity("SmartStockV1.Models.DetalleCompra", b =>
                {
                    b.Navigation("ItemsDetalleCompra");
                });

            modelBuilder.Entity("SmartStockV1.Models.DetalleCompraItem", b =>
                {
                    b.Navigation("MovimientosStock");
                });

            modelBuilder.Entity("SmartStockV1.Models.DetalleVenta", b =>
                {
                    b.Navigation("ItemsDetalleVenta");
                });

            modelBuilder.Entity("SmartStockV1.Models.DetalleVentaItem", b =>
                {
                    b.Navigation("MovimientosStock");
                });

            modelBuilder.Entity("SmartStockV1.Models.Dia", b =>
                {
                    b.Navigation("CajaDia");

                    b.Navigation("CompraDia");

                    b.Navigation("VentaDia");
                });

            modelBuilder.Entity("SmartStockV1.Models.Producto", b =>
                {
                    b.Navigation("DetallesCompraItem");

                    b.Navigation("DetallesVentaItem");

                    b.Navigation("MovimientosStock");
                });

            modelBuilder.Entity("SmartStockV1.Models.Proveedor", b =>
                {
                    b.Navigation("DetallesCompra");
                });

            modelBuilder.Entity("SmartStockV1.Models.Rol", b =>
                {
                    b.Navigation("UsuariosCreados");
                });

            modelBuilder.Entity("SmartStockV1.Models.Usuario", b =>
                {
                    b.Navigation("CategoriasCreadas");

                    b.Navigation("DetallesCompra");

                    b.Navigation("DetallesVenta");

                    b.Navigation("ProductosCreados");

                    b.Navigation("ProveedoresCreados");
                });

            modelBuilder.Entity("SmartStockV1.Models.VentaDia", b =>
                {
                    b.Navigation("DetallesVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
